cabal-version:      2.4
name:               op-energy-offer-api
version:            0.1.0.0

executable op-energy-offer-api
    main-is:          Main.hs
    build-depends:    base ^>=4.15.1.0
                    , servant, servant-swagger
                    , swagger2
                    , op-energy-offer-api
                    , aeson
                    , bytestring
    hs-source-dirs:   app
    default-language: Haskell2010

library
    hs-source-dirs: src
    exposed-modules: Data.OpEnergy.Offer.API
                   , Data.OpEnergy.Offer.API.V1.OfferStatus
                   , Data.OpEnergy.Offer.API.V2
                   , Data.OpEnergy.Offer.API.V2.PostOfferAPI
                   , Data.OpEnergy.Offer.API.V2.OffersAPI
                   , Data.OpEnergy.Offer.API.V2.CancelAPI

    build-depends:    base ^>=4.15.1.0
                    , aeson
                    , text
                    , bytestring
                    , servant, servant-swagger
                    , swagger2
                    , time
                    , lens
                    , persistent
                    , persistent-template
                    , op-energy-api
                    , op-energy-account-api

    ghc-options:    -O2 -Wall -Werror -Wno-unticked-promoted-constructors -fno-warn-name-shadowing -Wno-orphans
